name: Build and push Docker image with CGO

on:
  workflow_dispatch: # 手动触发 workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.2' # 或者您需要的 Go 版本

      - name: Install CGO dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential upx

      - name: Build with CGO
        run: |
          export CGO_ENABLED=1
          go build -o wp2ai -ldflags -w main.go
          upx -9 wp2ai

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wp2ai:latest